### ISSUE TITLE
Build on macos 10.15.3 Error

### ISSUE THREAD

**Issue by tuanictu97** [threema-ch/webrtc-build-docker#23]
Build on macos 10.15.3 Error:
Traceback (most recent call last):
  File "/opt/depot_tools/ninjalog_uploader_wrapper.py", line 125, in <module>
    sys.exit(main())
  File "/opt/depot_tools/ninjalog_uploader_wrapper.py", line 78, in main
    config = LoadConfig()
  File "/opt/depot_tools/ninjalog_uploader_wrapper.py", line 33, in LoadConfig
    ninjalog_uploader.IsGoogler('chromium-build-stats.appspot.com'),
  File "/opt/depot_tools/ninjalog_uploader.py", line 43, in IsGoogler
    _, content = h.request('https://' + server + '/should-upload', 'GET')
  File "/root/.vpython-root/c41d85/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/root/.vpython-root/c41d85/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/root/.vpython-root/c41d85/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1355, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1077, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady

**Comment by dbrgn** [comment]
Hm, I've never seen that error before. Maybe it was a temporary failure? Did you retry?

Anyways, this doesn't seem to have anything to do with our Docker setup, so I'll close the issue.
